### ISSUE TITLE
Install v0.6.0 failed

### ISSUE THREAD

**Issue by RainbowMango** [engineerd/setup-kind#255]
Hi, 

When bumping to the latest v0.6.0, an error raised as follows:
```
Download action repository 'engineerd/setup-kind@v0.6.0' (SHA:dfca6572a7497bbd1bb14e5ad473f8a1ba864ca6)
Error: Could not find file '/home/runner/work/_actions/_temp_743e1be1-95da-4e68-a43f-6f39a38772c9/_staging/engineerd-setup-kind-dfca657/node_modules/.bin/json5'.
```

PR: https://github.com/kubernetes-sigs/work-api/pull/46
Logs: https://github.com/kubernetes-sigs/work-api/actions/runs/11449128718/job/31854057178?pr=46
Usage: https://github.com/kubernetes-sigs/work-api/blob/0729a000bdbf6f16443b6697b3f99acdcd01c092/.github/workflows/ci.yml#L81-L84

**Comment by radu-matei** [comment]
v0.6.2 has now been released and should fix the issue.

Thank you for your patience!

**Comment by RainbowMango** [comment]
Thank you @radu-matei for the notice, I'm waiting for the dependabot to bump to that version, which is planned for next Monday.

**Comment by vrubezhny** [comment]
@radu-matei , 

Unfortunately, bumping to v.0.6.2 doesn't help... The following change:
```diff
-      - uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 #v0.5.0
+      - uses: engineerd/setup-kind@71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1 #v0.6.2
```

...still doesn't allow to install Kind failing as:

```
Run engineerd/setup-kind@71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1
  with:
    version: v0.11.1
    name: kind
    wait: 300s
    skipClusterCreation: false
    skipClusterDeletion: false
    skipClusterLogsExport: false
    verbosity: 0
    quiet: false
Error: File not found: '/home/runner/work/_actions/engineerd/setup-kind/71e45b960fc8dd50b4aeabf6eb6ef[2](https://github.com/redhat-developer/vscode-openshift-tools/actions/runs/11674705059/job/32508065342?pr=4612#step:6:2)ca0920b4c1/dist/main/index.js'
```

- PR: https://github.com/redhat-developer/vscode-openshift-tools/pull/4612

Any thoughts?

**Comment by RainbowMango** [comment]
It works for me, see https://github.com/kubernetes-sigs/work-api/pull/48.

But I'm not using commit hash but tag version v0.6.2.

**Comment by vrubezhny** [comment]
@RainbowMango Thanks for the hint!  Updating it using `v0.6.2` tag version worked fine:
```
- uses: engineerd/setup-kind@v0.6.2
```

**Comment by yorugac** [comment]
Hello! I've encountered the same issue: the [workflow](https://github.com/grafana/k6-operator/actions/runs/14751185239/workflow#L57) works with tag `v0.6.2` but not with the commit `71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1`. Is it known why it is so? 
Our recent security policy requires us to use commit hashes for external actions instead of versions. So I can't really go back to using the version. At the same time, [here](https://github.com/engineerd/setup-kind/tags), shouldn't this tag `v0.6.2` be exactly the same as that commit hash? It looks like some packaging problem to me 😕

**Comment by chalharu** [comment]
I found the cause. The tag v0.6.2 currently points to
71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1, but the actual HEAD of the
v0.6.2 branch is:

  ecfad61750951586a9ef973db567df1d28671bdc

This commit includes the built dist/ directory, so you need to pin to
ecfad61... instead of 71e45b9....
